[phases.setup]
nixPkgs = ['bun', 'nodejs']
aptPkgs = ['build-essential']

[phases.install]
cmd = 'bun install --frozen-lockfile'

[phases.build]
cmd = 'bun run build'

[start]
cmd = 'bun run start'

[environment]
COREPACK_ENABLE_STRICT = "0"
